src/assets/scss/_buttons.scss
src/assets/scss/components/_associated-systems.scss
src/assets/scss/components/_guides.scss
src/assets/scss/components/_sub-nav.scss
src/assets/scss/components/_thumbnail.scss
src/layouts/partials/guides/all_guides.html
src/layouts/partials/thumbnail/excerpt.html

makes changes to home page cards, filter and headings

6 increase card desc char length

---

src/content/measurement_techniques/motor-runtime.md
src/layouts/shortcodes/calculation_methodology.html
src/layouts/shortcodes/measurement_technique.html

adds related components to the measurements technique content .md for motor runtime

8 review and adjust what realted items

---

src/assets/scss/components/_guides.scss
src/content/guides/components/constant-speed-constant-volume-pump-motor.md
src/content/guides/components/liquid-to-liquid-heat-exchanger.md
src/content/guides/plants/water-cooled-chilled-water-plant.md
src/content/guides/systems/chilled-water-loop.md
src/content/guides/systems/condenser-water-loop.md
src/content/guides/systems/water-cooled-chiller.md
src/content/guides/systems/waterside-economizer.md
src/layouts/partials/footer.html
src/layouts/partials/head.html
src/static/css/lightbox.css
src/static/js/guides.js
src/static/js/lightbox.js

a tags allow lightbox to activate

adds hugo codex lightbox and anchor tags on every image

---

src/content/measurement_techniques/motor-runtime.md

Added numbers to the headers of the steps in the Motor Runtime.

Part 2 of making changes

---

src/assets/scss/components/_sub-nav.scss
src/content/guides/plants/water-cooled-chilled-water-plant copy 10.md
src/content/guides/plants/water-cooled-chilled-water-plant copy 2.md
src/content/guides/plants/water-cooled-chilled-water-plant copy 3.md
src/content/guides/plants/water-cooled-chilled-water-plant copy 4.md
src/content/guides/plants/water-cooled-chilled-water-plant copy 5.md
src/content/guides/plants/water-cooled-chilled-water-plant copy 6.md
src/content/guides/plants/water-cooled-chilled-water-plant copy 7.md
src/content/guides/plants/water-cooled-chilled-water-plant copy 8.md
src/content/guides/plants/water-cooled-chilled-water-plant copy 9.md
src/data/plants.yml
src/layouts/partials/guides/all_guides.html
src/static/js/guides.js

**AUD**: https://trello.com/c/YiWbIrQ3
**Requirements**:
- Go to `src/layouts/partials/guides/all_guides.html`
- Create a Hugo variable that will serve as a counter for displayed guides
- Add a condition for displaying the "Load More X" button, if the displayed guides are less than the default number of displayed guides, don't render the button
**Main Changes**:
- I added dummy guide pages so the changes in the "Load More X" button can be tested
- Made functionality that hides the "Load More X" button when all the guides are displayed
- I fixed an issue where all the guides are displayed on page load and the maximum number of guides is not honored
**Tests**:
- I tested the changes on my local machine

Improve UX of "Load More X" button

---

src/content/calculation_methodologies/lighting-plant-and-systems-energy-consumption.md

I put two notes for where the footnotes will go @mascazubi 
Here is the content of both footnotes (both footnotes are the same text):
CUNY BPL recommends taking a sample of measurements and find the average. The average value will be used to calculate annual energy consumption. As an example, the Onset HOBO 4-channel analog logger can measure a sample of current data at a predefined interval known as the sampling interval. If the logging interval is set to one-hour and the sampling interval is set to one-second, the logger will measure current every second for one hour then determine the average. The average will be stored in the logger as the one-hour interval measurement. This process will continue every hour for the duration of the measurement period. 
(Use for both footnotes)

Finished the Lighting Calculation Methodology, put 2 notes for the footnotes in the text

---

src/data/calculations.yml
src/data/measurements.yml

Edited the data of the code to show missing pages. Will iron out final details on the pages afterwards.

Edited data to show missing pages

---

src/content/guides/components/variable-speed-variable-volume-pump-and-motor.md
src/content/guides/systems/chilled-water-loop.md
src/content/guides/systems/condenser-water-loop.md
src/content/guides/systems/hot-water-loop.md

Will work on more tables for other pages once Orlando gives the green light 👍🏾

Updated a few tables for systems and one component

---

src/assets/scss/components/_guides.scss
src/content/calculation_methodologies/cooling-tower-fans-energy-consumption.md
src/content/calculation_methodologies/fan-motors-energy-consumption.md
src/content/calculation_methodologies/lighting-plant-and-systems-energy-consumption.md
src/content/calculation_methodologies/pump-motors-energy-consumption.md
src/content/measurement_techniques/water-pressure-and-pump-curve.md

class for text that needs to be in same line as steps and increase left margin of equations

adds indent-step class and increases equation left margin

---

src/content/guides/systems/air-cooled-chiller.md
src/content/guides/systems/boiler.md
src/content/guides/systems/chilled-water-loop.md
src/content/guides/systems/condenser-water-loop.md
src/content/guides/systems/constant-speed-constant-volume-air-handling-system.md
src/content/guides/systems/electrical-distribution.md
src/content/guides/systems/hot-water-loop.md
src/content/guides/systems/lighting-fixture.md
src/content/guides/systems/variable-speed-variable-volume-air-handling-system.md
src/content/guides/systems/water-cooled-chiller.md
src/content/guides/systems/waterside-economizer.md

@mascazubi Will have to teach me how to merge separate boxes in tables such as how it's done for the water cooled chiller table

Updated tables for boiler, water cooled chiller, and air cooled chiller

---

src/content/calculation_methodologies/cooling-tower-fans-energy-consumption.md
src/content/calculation_methodologies/fan-motors-energy-consumption.md
src/content/calculation_methodologies/lighting-plant-and-systems-energy-consumption.md
src/content/calculation_methodologies/liquid-to-liquid-heat-exchanger-heat-transfer.md
src/content/calculation_methodologies/pump-motors-energy-consumption.md

Made all of the changes mentioned on the doc. Orlando (@SideSwipeX01) will give missing introductions for Fan and Pump Calculation Methodology pages and will update when given.

Made the changes to the calc pages as mentioned on the document

---

src/assets/scss/components/_navbar.scss
src/config/_default/config.toml
src/layouts/partials/navbar.html

brings back the nycet nav with a minimalistic look

150 add back the nycet nav

---

src/content/guides/components/air-to-air-heat-exchanger.md
src/content/guides/components/liquid-to-liquid-heat-exchanger.md
src/content/guides/components/variable-speed-variable-volume-fan-and-motor.md
src/content/guides/plants/air-handling-plant.md
src/content/guides/systems/air-cooled-chiller.md
src/content/guides/systems/boiler.md
src/content/guides/systems/constant-speed-constant-volume-air-handling-system.md
src/content/guides/systems/electrical-distribution.md
src/content/guides/systems/steam-condensate-recovery.md
src/content/guides/systems/variable-speed-variable-volume-air-handling-system.md
src/content/guides/systems/water-cooled-chiller.md
src/content/measurement_techniques/electrical-current.md
src/content/measurement_techniques/electrical-spot-measurement.md
src/content/measurement_techniques/lighting-fixture-runtime.md
src/content/measurement_techniques/motor-runtime.md
src/content/measurement_techniques/outdoor-air-temperature.md
src/content/measurement_techniques/pipe-surface-water-temperature.md
src/content/measurement_techniques/relative-humidity.md
src/content/measurement_techniques/system-air-temperature.md
src/content/measurement_techniques/true-rms-power.md
src/content/measurement_techniques/water-flow-rate.md
src/content/measurement_techniques/water-pressure-and-pump-curve.md

Did _not change_ the footnote text in the table to avoid confusion. Will discuss with @mascazubi on how to update all of the footnotes in the PnP page using a new system.

Updated site connections between pages

---

src/static/js/guides.js
src/static/js/search.js

- https://trello.com/c/3MIKwBN6
- Check the current behavior of the search bar
- In src/static/js/guides.js, remove the condition that checks if the keyword in search bar is included in the title, and contents of the guides, measurement techniques and calculation methodologies
- Test the changes in local environment
- Modified `src/static/js/guides.js` to update the conditions in these functions:
- `filterPlantGuides()`
- `filterSystemGuides()`
- `filterComponentGuides()`
- `filterCalculations()`
- `filterMeasurements()`
- I tested the changes in local environment

Update algoritm of search bar

---

src/static/js/guides.js
src/static/js/search.js

- https://trello.com/c/3MIKwBN6
- In `src/static/js/guides.js`, ignore the hyphen in the search keyword for the guides, measurement techniques and calculation methodologies
- Update the search algorithm
- I tested the changes in local environment

Update the search algorithm

---

src/content/calculation_methodologies/lighting-plant-and-systems-energy-consumption.md
src/content/guides/components/variable-speed-variable-volume-pump-and-motor.md
src/content/guides/plants/steam-plant.md
src/content/measurement_techniques/water-pressure-and-pump-curve.md

Added new formula to one of the calculation pages, as well as other small changes to the website. Will upload next changes to the calculation equations once Orlando comes back next week.

Made new changes to website

---

src/assets/scss/_common.scss
src/assets/scss/components/_footer-section.scss
src/assets/scss/components/_guides.scss
src/assets/scss/components/_hero-section.scss
src/assets/scss/components/_navbar.scss
src/assets/scss/components/_sub-nav.scss
src/data/page_tabs.yml
src/layouts/partials/basic/content.html
src/layouts/partials/calculation_methodology/content.html
src/layouts/partials/guides/content.html
src/layouts/partials/guides/header.html
src/layouts/partials/measurement_technique/content.html

all changes related to improving tab buttons in content pages and to macth hero home page tabs + QOL enhancements

208 tab buttons updates

---

src/content/guides/components/constant-speed-constant-volume-compressor-and-motor.md
src/content/guides/components/liquid-to-liquid-heat-exchanger.md
src/content/guides/systems/chilled-water-loop.md
src/content/guides/systems/hot-water-loop.md
src/content/guides/systems/steam-condensate-recovery.md
src/data/components.yml

Still need to add figure 1 to the component page, and link to measurement equipment. Ignored water flow rate videos.

Made changes to website and added new component page

---

src/content/guides/components/air-to-air-heat-exchanger.md
src/content/guides/components/constant-speed-constant-volume-fan-and-motor.md
src/content/guides/components/liquid-to-liquid-heat-exchanger.md
src/content/guides/components/variable-speed-variable-volume-fan-and-motor.md
src/content/guides/components/variable-speed-variable-volume-pump-and-motor.md
src/content/guides/systems/air-cooled-chiller.md
src/content/guides/systems/water-cooled-chiller.md

Some of the quick fix changes are a bit confusing, so will discuss with team before implement the rest of them.

Updated tables for component pages, and implemented some quick fix changes

---

src/assets/scss/components/_guides.scss
src/layouts/partials/guides/all_guides.html

adds styles for the details and child elements

replaces definition text p with details element

---

src/content/measurement_techniques/electrical-current.md
src/content/measurement_techniques/electrical-spot-measurement.md
src/content/measurement_techniques/lighting-fixture-runtime.md
src/content/measurement_techniques/motor-runtime.md
src/content/measurement_techniques/outdoor-air-temperature.md
src/content/measurement_techniques/pipe-surface-water-temperature.md
src/content/measurement_techniques/relative-humidity.md
src/content/measurement_techniques/system-air-temperature.md
src/content/measurement_techniques/true-rms-power.md
src/content/measurement_techniques/water-flow-rate.md
src/content/measurement_techniques/water-pressure-and-pump-curve.md

Removed all of the unecessary figures from the measurement pages, and added the embeded videos for each step. Also made edits to some headers and the lists for the individual steps. @SideSwipeX01 please check the pages once merged to make sure everything is good to go!

Measurement page changes

---

src/content/glossary/_index.md
src/content/measurement_techniques/electrical-current.md
src/content/measurement_techniques/electrical-spot-measurement.md
src/content/measurement_techniques/lighting-fixture-runtime.md
src/content/measurement_techniques/motor-runtime.md
src/content/measurement_techniques/outdoor-air-temperature.md
src/content/measurement_techniques/pipe-surface-water-temperature.md
src/content/measurement_techniques/relative-humidity.md
src/content/measurement_techniques/system-air-temperature.md
src/content/measurement_techniques/true-rms-power.md
src/content/measurement_techniques/water-flow-rate.md

Can close issue #234 (fixing the calculators for measurement pages).

Updated glossary with spelt out terms and rearranged alphabetically. Also fixed calculator bug in measurement pages

---

src/assets/scss/components/_guides.scss
src/assets/scss/components/_hero-section.scss
src/assets/scss/components/_measurement-technique.scss
src/assets/scss/components/_sub-nav.scss
src/assets/scss/components/_thumbnail.scss
src/content/guides/components/air-to-air-heat-exchanger.md
src/content/guides/systems/air-to-air-energy-recovery.md
src/layouts/partials/basic/content-glossary.html
src/layouts/partials/basic/content.html
src/layouts/partials/calculation_methodology/content.html
src/layouts/partials/guides/content.html
src/layouts/partials/hero.html
src/layouts/partials/measurement_technique/content.html
src/layouts/partials/sub_nav/horizontal_nav.html
src/layouts/shortcodes/calculation_methodology.html
src/layouts/shortcodes/downloadable_file.html
src/layouts/shortcodes/measurement_technique.html
src/layouts/shortcodes/page_hyperlink.html

combines minimal responsive style updates and updates to short codes with examples in the air-air-hx component page

259 semi responsive updates

---

src/assets/js/cy.js
src/assets/scss/_variables.scss
src/assets/scss/components/_hero-section.scss
src/layouts/partials/head.html
src/layouts/partials/sitemap/cytoscape.html

renames sitemap and adds/updates styles

265 rename sitemap chart thoughout app

---

src/content/guides/soos/airside-economizing.md
src/content/guides/soos/chilled-water-supply-temperature-reset.md
src/content/guides/soos/static-pressure-reset-ahu.md
src/content/guides/soos/supply-air-temperature-reset.md
src/content/guides/soos/waterside-economizer.md

Tasks listed in issue 315 (https://github.com/cunybpl/nycet_pnp/issues/315) are completed.

Complete tasks for issue 315

---

src/assets/scss/components/_measurement-technique.scss
src/content/measurement_techniques/electrical-current.md
src/content/measurement_techniques/electrical-spot-measurement.md
src/content/measurement_techniques/lighting-fixture-runtime.md
src/content/measurement_techniques/motor-runtime.md
src/content/measurement_techniques/outdoor-air-temperature.md
src/content/measurement_techniques/pipe-surface-water-temperature.md
src/content/measurement_techniques/relative-humidity.md
src/content/measurement_techniques/system-air-temperature.md
src/content/measurement_techniques/true-rms-power.md
src/content/measurement_techniques/water-flow-rate.md
src/content/measurement_techniques/water-pressure-and-pump-curve.md

Will discuss this further with rest of team

fixed bullet errors in 2 measurement pages
